queue_rules:
  - name: default
    # Mergify always respects the branch protection settings
    # so we can left empty mergify own ones
    queue_conditions:
      - label=merge me
    merge_conditions: []
    merge_method: squash

pull_request_rules:
  - name: Automatically merge pull requests
    conditions: []
    actions:
      queue:
